name: Apply
on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  TF_VAR_github_app_id: ${{ vars.GH_APP_ID }}
  TF_VAR_github_app_installation_id: ${{ vars.GH_APP_INSTALLATION_ID }}
  TF_VAR_github_app_pem_file: ${{ secrets.GH_APP_PEM_FILE }}

jobs:
  apply:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.apply.outputs.stdout }}
      outcome: ${{ steps.apply.outcome }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
      - name: init
        run: terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: apply
        id: apply
        run: terraform apply -no-color -auto-approve
  comment:
    uses: ./.github/workflows/comment.yml
    needs: apply
    with:
      mode: apply
      result: ${{ needs.apply.outputs.result }}
      outcome: ${{ needs.apply.outputs.outcome }}
